template_files = [ "header.html", "footer.html" ]

data_files = [ "data/site.json" ]

[data_queries]
Posts = "queries/posts.sql"

[data_functions]
Posts = "github.com/bokwoon95/pagemanager.GetPosts -fields=abc,def,ghi"

[content_security_policy]
script-src = [ "stackpath.bootstrapcdn.com", "code.jquery.com" ]
style-src = [ "stackpath.bootstrapcdn.com", "fonts.googleapis.com" ]
img-src = [ "source.unsplash.com", "images.unsplash.com" ]
font-src = [ "fonts.gstatic.com" ]
